CREATE TABLE type (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(15) NOT NULL, libelle VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8CDE572977153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE film (id INT AUTO_INCREMENT NOT NULL, type_id INT NOT NULL, support_id INT NOT NULL, titre VARCHAR(50) NOT NULL, sousTitre VARCHAR(50) DEFAULT NULL, anneeSortie INT NOT NULL, resume LONGTEXT DEFAULT NULL, INDEX IDX_8244BE22C54C8C93 (type_id), INDEX IDX_8244BE22315B405 (support_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE film_genre (film_id INT NOT NULL, genre_id INT NOT NULL, INDEX IDX_1A3CCDA8567F5183 (film_id), INDEX IDX_1A3CCDA84296D31F (genre_id), PRIMARY KEY(film_id, genre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE support (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(15) NOT NULL, libelle VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_8004EBA577153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE genre (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(15) NOT NULL, libelle VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_835033F877153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE film ADD CONSTRAINT FK_8244BE22C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id);
ALTER TABLE film ADD CONSTRAINT FK_8244BE22315B405 FOREIGN KEY (support_id) REFERENCES support (id);
ALTER TABLE film_genre ADD CONSTRAINT FK_1A3CCDA8567F5183 FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE;
ALTER TABLE film_genre ADD CONSTRAINT FK_1A3CCDA84296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;
