<?php

namespace Patlenain\VideotekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Film Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Film Repository extends EntityRepository
{
}
