<?php

namespace Patlenain\VideotekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
	/**
	 * @return QueryBuilder
	 */
	function listAll()
	{
		return $this->createQueryBuilder('type')
			->addOrderBy('type.libelle', 'DESC');
	}
}
